feat(git): remove github cli (and direnv)

diff --git a/remove_dot_local/remove_bin/executable_:sync.tmpl b/remove_dot_local/remove_bin/executable_:sync.tmpl
--- a/remove_dot_local/remove_bin/executable_:sync.tmpl
+++ b/remove_dot_local/remove_bin/executable_:sync.tmpl
@@ -2,15 +2,19 @@
 
 #!/usr/bin/env bash
 #
-# A script to clone/fork/sync multiple git repos listed in a file in a sequence
-# using the `gh` command line tool. The input file should have the following
-# structure:
-#
-# (space)*(operation: [clone | fork])(space)+(url)(space)+(directory)(space)*
+# A script to clone or update (fetch) multiple git repos listed in a file in a
+# sequence. The input file should have lines containing the target directory
+# and the full remote separated by whitespace.
 #
 # Empty lines and those beginning with hash (#) are ignored.
+#
+# The (-f) option can be used to skip fetch and just clone repos where needed.
 
 set -euo pipefail
+
+DIRECTORY_COLOR='\033[0;34m' # blue
+URL_COLOR='\033[0;36m'       # cyan
+RESET_COLOR='\033[0m'
 
 FAST=false
 while getopts "f" option; do
@@ -33,9 +37,12 @@ if [[ ! -f "${LIST_FILE}" ]]; then
 	exit 1
 fi
 
+function trying_to {
+	>&2 printf ">> %s ${URL_COLOR}%s${RESET_COLOR} %s ${DIRECTORY_COLOR}%s${RESET_COLOR}\n" "${1}" "${2}" "${3}" "${4}"
+}
+
 function failed_to {
-	#printf "\e[31m✗\e[m Failed to %s \e[36m%s\e[m to \e[34m%s\e[m\n" "${1}" "${2}" "${3}"
-	>&2 printf "\e[31m✗\e[m Failed to %s %s to %s\n" "${1}" "${2}" "${3}"
+	>&2 printf "${RED}%s${RESET_COLOR} Failed to %s ${URL_COLOR}%s${RESET_COLOR} %s ${DIRECTORY_COLOR}%s${RESET_COLOR}\n" "✗" "${1}" "${2}" "${3}" "${4}"
 }
 
 function read_list_from {
@@ -44,19 +51,16 @@ function read_list_from {
 
 while read -r line; do
 	target="$(echo "${line}" | cut -f1)"
-	cmd="$(echo "${line}" | cut -f2)"
-	repo="$(echo "${line}" | cut -f3)"
+	remote="$(echo "${line}" | cut -f2)"
 
 	if [[ -d "${target}" ]]; then
 		if ! ${FAST}; then
-			(cd "${target}"; gh repo sync || failed_to 'sync' "${repo}" "${target}")
+			trying_to 'Fetching'  "${remote}" 'at' "${target}"
+			git -C "${target}" fetch || failed_to 'fetch' "${remote}" 'at' "${target}"
 		fi
 	else
-		case ${cmd} in
-			clone) gh repo clone "${repo}" "${target}" || failed_to 'clone' "${repo}" "${target}" ;;
-			fork)  gh repo fork --clone "${repo}" "${target}" || failed_to 'fork and clone' "${repo}" "${target}" ;;
-			*) failed_to "${cmd}" "${repo}" "${target}"
-		esac
+		trying_to 'Cloning'  "${remote}" 'to' "${target}"
+		git clone "${remote}" "${target}" || failed_to 'clone' "${remote}" 'to' "${target}"
 	fi
 done < <(read_list_from "${LIST_FILE}")
 
