fix(git): handle missing file in :sync

diff --git a/dot_local/bin/executable_:sync b/dot_local/bin/executable_:sync
--- a/dot_local/bin/executable_:sync
+++ b/dot_local/bin/executable_:sync
@@ -22,6 +22,11 @@ if [[ ${#} -eq 0 ]]; then
 fi
 LIST_FILE=${1:-${DEFAULT_LIST_FILE}}
 
+if [[ ! -f "${LIST_FILE}" ]]; then
+	echo "Could not find ${LIST_FILE}"
+	exit 1
+fi
+
 function failed_to {
 	#printf "\e[31m✗\e[m Failed to %s \e[36m%s\e[m to \e[34m%s\e[m\n" "${1}" "${2}" "${3}"
 	>&2 printf "\e[31m✗\e[m Failed to %s %s to %s\n" "${1}" "${2}" "${3}"
